services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: clasificador-documentos-postgres
    environment:
      POSTGRES_DB: clasificador_documentos_ia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: clasificador-documentos-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: