"""add file fields to documents

Revision ID: 2cb74d251fe3
Revises: bc2d6263783b
Create Date: 2026-03-22 14:27:03.468786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb74d251fe3'
down_revision: Union[str, Sequence[str], None] = 'bc2d6263783b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('stored_filename', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('file_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'stored_filename')
    # ### end Alembic commands ###
