"""add document summaries table

Revision ID: 3b81556edda1
Revises: 7bb2a60919f8
Create Date: 2026-03-22 16:57:26.726197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b81556edda1'
down_revision: Union[str, Sequence[str], None] = '7bb2a60919f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('short_summary', sa.Text(), nullable=False),
    sa.Column('key_points', sa.Text(), nullable=True),
    sa.Column('keywords', sa.String(length=500), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_summaries_document_id'), 'document_summaries', ['document_id'], unique=True)
    op.create_index(op.f('ix_document_summaries_id'), 'document_summaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_summaries_id'), table_name='document_summaries')
    op.drop_index(op.f('ix_document_summaries_document_id'), table_name='document_summaries')
    op.drop_table('document_summaries')
    # ### end Alembic commands ###
