"""add document texts table

Revision ID: 431496fe37a3
Revises: 2cb74d251fe3
Create Date: 2026-03-22 14:37:11.757413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431496fe37a3'
down_revision: Union[str, Sequence[str], None] = '2cb74d251fe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_texts_document_id'), 'document_texts', ['document_id'], unique=True)
    op.create_index(op.f('ix_document_texts_id'), 'document_texts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_texts_id'), table_name='document_texts')
    op.drop_index(op.f('ix_document_texts_document_id'), table_name='document_texts')
    op.drop_table('document_texts')
    # ### end Alembic commands ###
