"""add document classifications table

Revision ID: 7bb2a60919f8
Revises: 431496fe37a3
Create Date: 2026-03-22 16:48:41.302893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bb2a60919f8'
down_revision: Union[str, Sequence[str], None] = '431496fe37a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('matched_keywords', sa.Text(), nullable=True),
    sa.Column('classified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_classifications_document_id'), 'document_classifications', ['document_id'], unique=True)
    op.create_index(op.f('ix_document_classifications_id'), 'document_classifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_classifications_id'), table_name='document_classifications')
    op.drop_index(op.f('ix_document_classifications_document_id'), table_name='document_classifications')
    op.drop_table('document_classifications')
    # ### end Alembic commands ###
